#!/usr/bin/env ruby

$LOAD_PATH << "lib"
require 'zellers'
require 'month_convert'
require 'month'
#require 'year'

## Print this month
if ARGV.length == 0
  month = Time.now.strftime("%m").to_i
  year = Time.now.strftime("%Y").to_i
  zeller = Zellers.new(month, year)

## Year method
elsif ARGV.length == 1
  year = ARGV[0].to_i
  zeller = Zellers.new(1, year)
  some_array = print_month(1, year, zeller).to_s

## Full month string method
elsif ARGV[0].to_i == 0
  month = month_string(ARGV[0])
  year = ARGV[1].to_i
  zeller = Zellers.new(month, year).to_s

## Month and year method
elsif ARGV.length == 2
  month = ARGV[0].to_i
  year = ARGV[1].to_i
  zeller = Zellers.new(month, year)
else
  raise ArgumentError, 'too many arguments :( sadface'
end

#Print
if month
  month = find_month(month)
  print_month(month, year, zeller)
end
